@startuml German Games

'classes
abstract class Gender {
    {abstract} get_gender()
}
class GenderDet_Gender
class Pattern_Gender
class Ensemble_Gender

abstract class Article {
    {abstract} get_article()
}
class Pattern_Article
class Lookup_Article

class Grammar {
    pronouns
    get_gender()
    get_article()
    get_conjverb()
}
class Database {
    load_duolingo()
    load_separables()
}

abstract class Controller {
    {abstract} run()
    {abstract} end()
}
class GameController {
    life
    success
    check_answer()
}
class MenuController {
    games
    setup()
    load_game()
}

abstract class Game{
    {abstract} generate_question()
    {abstract} generate_answer()
    {abstract} generate_prompt()
}
class GuessArticle {
    nouns
    cases
    forms
}

class MenuView {
    choose_a_game()
}
class GameView {
    check_message()
    show_score()
}

'libraries
entity genderdeterminator
entity pattern
entity json

' dependencies
Grammar ..> Gender: uses
Grammar ..> Article: uses

Ensemble_Gender ..> GenderDet_Gender: uses
Ensemble_Gender ..> Pattern_Gender: uses

Game ..> Grammar: uses

GameController ..> Game: uses
GameController ..> GameView: uses

MenuController ..> MenuView: uses
MenuController ..> Database: uses
MenuController ..> GuessArticle: uses
MenuController ..> GameController: uses

' implementations
Gender <|.. GenderDet_Gender
Gender <|.. Pattern_Gender
Gender <|.. Ensemble_Gender

Article <|.. Pattern_Article
Article <|.. Lookup_Article

Controller <|.. GameController
Controller <|.. MenuController 

Game <|.. GuessArticle

' libraries
GenderDet_Gender ..> genderdeterminator: imports
Pattern_Gender ..> pattern: imports
Lookup_Article ..> json: imports

@enduml